spring:
  kafka:
    listener:
      missing-topics-fatal: false
      ack-mode: manual
    bootstrap-servers: localhost:8762
    consumer:
      group-id: stock-service
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Correct deserializer for key
      #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer  # Correct deserializer for value
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
          deserializer:
            value:
              delegate:
                class: com.stock.config.DynamicJsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Correct serializer for key
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Correct serializer for value

#  topics:
#    orderCreate: order-created
#    orderFail: order-failed
